export { default as Pricing} from './blog/blog'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Possibility } from './possibility/Possibility'
export { default as About } from './whatFGT/WhatGPT'
export {default as Terms} from './term/Term'
export {default as Privacy} from './privacy/Privacy'
